package com.example.newp

val A = listOf(
    "IN - AN",
    "IN - AP",
    "IN - AR",
    "IN - CH",
    "IN - AS",
    "IN - BR",
    "IN - CT",
   " IN - DD",

    "IN - DL",
    "IN - DN",
    "IN - GA",
    "IN - GJ",
    "IN - HP",
    "IN - HR",
    "IN - JH",
    "IN - JK",
    "IN - KA",
    "IN - KL",
    "IN - LD",
    "IN - MH",
    "IN - ML",
    "IN - MN",
    "IN - MP",
    "IN - MZ",
    "IN - NL",
    "IN - OR",
    "IN - PB",
    "IN - PY",
    "IN - RJ",
    "IN - SK",
    "IN - TG",
    "IN - TN",
    "IN - TR",
    "IN - UP",
    "IN - UT",
    "IN - WB",
)